/**
 * Standard error code catalog.
 *
 * Convention:
 * - UPPER_SNAKE_CASE
 * - First token = domain (e.g., AUTH_, MENU_, ORDER_, TABLE_)
 * - Append-only within each section. Do not modify other Unit's entries.
 */
export const ErrorCodes = {
  // ── Foundation (공통) ──────────────────────────────────────
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // ── Unit 1 (Auth) ──────────────────────────────────────────
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',

  // ── Unit 2 (Menu) ──────────────────────────────────────────
  MENU_NOT_FOUND: 'MENU_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_ITEMS: 'CATEGORY_HAS_ITEMS',
  DUPLICATE_CATEGORY_NAME: 'DUPLICATE_CATEGORY_NAME',
  PRICE_OUT_OF_RANGE: 'PRICE_OUT_OF_RANGE',
  INVALID_MENU_NAME: 'INVALID_MENU_NAME',
  INVALID_MENU_DESCRIPTION: 'INVALID_MENU_DESCRIPTION',
  INVALID_CATEGORY_NAME: 'INVALID_CATEGORY_NAME',
  INVALID_IMAGE_URL: 'INVALID_IMAGE_URL',

  // ── Unit 3 (Order + SSE) ───────────────────────────────────
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_EMPTY: 'ORDER_EMPTY',
  ORDER_PRICE_MISMATCH: 'ORDER_PRICE_MISMATCH',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  ORDER_ITEMS_OUT_OF_RANGE: 'ORDER_ITEMS_OUT_OF_RANGE',

  // ── Unit 4 (Table) ─────────────────────────────────────────
  TABLE_NOT_FOUND: 'TABLE_NOT_FOUND',
  DUPLICATE_TABLE_NUMBER: 'DUPLICATE_TABLE_NUMBER',
  TABLE_HAS_ACTIVE_SESSION: 'TABLE_HAS_ACTIVE_SESSION',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_ACTIVE: 'SESSION_NOT_ACTIVE',
  INVALID_TABLE_NUMBER: 'INVALID_TABLE_NUMBER',
  INVALID_TABLE_PASSWORD: 'INVALID_TABLE_PASSWORD',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
